# Generated by Django 3.2.8 on 2021-11-29 19:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
